FROM node:21-alpine3.18

WORKDIR /app
COPY package*.json ./
COPY tsconfig.json ./
COPY .npmrc ./
COPY package.json ./
COPY src ./src
RUN ls -a
# RUN npm run clean && npm install -g nodemon
RUN npm ci

EXPOSE 4000

CMD [ "npm", "run", "dev" ]
