FROM node:21-alpine3.18

WORKDIR /app
COPY tsconfig.json ./
COPY .npmrc ./
COPY tools ./tools
COPY local-packs ./local-packs
COPY package.json ./
COPY src ./src
RUN ls -a
# RUN npm run clean && npm install -g nodemon
RUN npm install

EXPOSE 4001

CMD [ "npm", "run", "dev" ]
