apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobber-auth
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobber-auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25% 
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: jobber-auth
    spec:
      containers:
      - name: jobber-auth
        image: mydockerid/3-auth-service
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "512Mi"
            cpu: '500m'
          requests:
            memory: 128Mi
            cpu: 100m
        ports:
        - name: auth
          containerPort: 4002
        env:
          - name: MS_NAME
            value: 'AuthMS'
          - name: SERVER_PORT
            value: '4002'
          - name: NODE_ENV
            value: 'production'
          - name: ENABLE_APM
            value: '1'
          - name: GATEWAY_JWT_TOKEN
            valueFrom:
              secretKeyRef:
                name: jobber-backend-secret
                key: gateway-jwt-token
          - name: JWT_TOKEN
            valueFrom:
              secretKeyRef:
                name: jobber-backend-secret
                key: jwt-token
          - name: CLOUD_NAME
            valueFrom:
              secretKeyRef:
                name: jobber-backend-secret
                key: cloud-name
          - name: CLOUD_API_KEY
            valueFrom:
              secretKeyRef:
                name: jobber-backend-secret
                key: cloud-api-key
          - name: CLOUD_API_SECRET
            valueFrom:
              secretKeyRef:
                name: jobber-backend-secret
                key: cloud-api-secret
          - name: USE_CLOUDINARY
            value: 'false'
          - name: CLIENT_URL
            value: 'https://jobberapp.info'
          - name: API_GATEWAY_URL
            value: 'http://jobber-gateway.production.svc.cluster.local:4000'
          - name: RABBITMQ_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: jobber-backend-secret
                key: jobber-rabbitmq-endpoint
          - name: MYSQL_DB
            valueFrom:
              secretKeyRef:
                name: jobber-backend-secret
                key: jobber-mysql-db
          - name: ELASTIC_SEARCH_URL
            valueFrom:
              secretKeyRef:
                name: jobber-backend-secret
                key: jobber-elasticsearch-url
          - name: ELASTIC_APM_SERVER_URL
            valueFrom:
              secretKeyRef:
                name: jobber-backend-secret
                key:  jobber-elastic-apm-server-url
          - name: ELASTIC_APM_SECRET_TOKEN
            valueFrom:
              secretKeyRef:
                name: jobber-backend-secret
                key: jobber-elastic-apm-secret-token
