FROM node:21-alpine3.18

WORKDIR /app
COPY package*.json ./
COPY tsconfig.json ./
COPY .npmrc ./
COPY src ./src
COPY local-packs ./local-packs

# RUN npm run clean && npm install -g nodemon
RUN npm ci

EXPOSE 4006

CMD [ "npm", "run", "dev" ]
