FROM node:21-alpine3.18

WORKDIR /app
COPY package*.json ./
COPY tsconfig.json ./
COPY .npmrc ./
COPY local-packs ./local-packs
COPY src ./src
RUN ls -a
# RUN npm run clean && npm install -g nodemon
RUN npm ci

EXPOSE 4002

CMD [ "npm", "run", "dev" ]
